services:
  urestic:
    image: wanxve0000/urestic:latest
    container_name: urestic
    ports:
      - "8085:8085"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - ./backups:/backups
      - ./sources:/sources:ro
      - ./restore:/restore
      - /root/.config/rclone/rclone.conf:/host-rclone/rclone.conf:ro
    restart: unless-stopped
